### ISSUE TITLE
Failed to prepare header for mining err="not authorized to sign: 0x34344833c2D4c793979D1fbe436589E22Cc3Ef3c"

### ISSUE THREAD

**Issue by EL-MehdiLoukach** [gochain/docs#135]
I'm trying to create two docker containers that will hold GoChain nodes for each one of them.

Everything goes well until I build the solution up with `docker-compose up -d`, both containers are running the nodes but one of them (the second) shows an error when docker logs -f node2 is executed :

> err="not authorized to sign: 0x00000000000000000000000f07A0b446F09afad7"

Also, when I try to add another peer to the first node by executing `admin.addPeers("enode://enode2adress@node2IP")`, the only response I get is true but no peers were added when I check with `admin.peers`, it returns an empty array.

Where could the source of the problem be ?

Thanks in advance !

**Comment by treeder** [comment]
This is for a private network? Have you voted in the second note to vote?

**Comment by EL-MehdiLoukach** [comment]
> This is for a private network? Have you voted in the second note to vote?

Yes it is for a private network, I actually didn't know how to use the `genesis.json` file, I had to add the signers, voters and allocators.. It works fine for now, Thanks for the reply 😄
