### ISSUE TITLE
Unable to sync chain in full mode and archive pruning. As result part of information

### ISSUE THREAD

**Issue by KursLabIgor** [gochain/docs#39]
Unable to sync chain in full mode and archive pruning.
**Ubuntu 16.04
Chain/v2.2.20/linux-amd64/go1.10.4 
Command for start:** 
`./gochain --rpc --ws --wsorigins "*" --rpcapi eth,net,web3,debug --wsapi eth,net,web3,debug --syncmode "full" --datadir /mnt/sdb/mainnet/node --gcmode "archive"`

`eth.getBlock(1000)
{
  difficulty: 5,
  extraData: "0x322e312e322f6c696e75782d616d6436342f676f312e31302e32000000000000",
  gasLimit: 210284448,
  gasUsed: 0,
  hash: "0x466ecb3ea37384ab82465c320add5bf40766e5751e4dfe4968331b0e46d205c5",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x3729d2e93e8037f87a2c9afe34cb84b7069e4dea",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 1000,
  parentHash: "0x3760455ec09a8c0ac6aa885cc843a43fd635304cec2583edf8007a9934f35615",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  signer: "0x78d5bfe08827b6b6ef7a623982011e307aa6aabaf1245b8aa508b0327dfadb690dfc0cee0fb357083f2e5821228fb9a8ce6aa15fd3f003345b02bb0dbfb8859b00",
  signers: [],
  size: 612,
  stateRoot: "0x0c3a92c84fd29ce5892f25dca3532619f3c16e576011e7ecba22564e39e78b32",
  timestamp: 1526438938,
  totalDifficulty: 4952,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: [],
  voters: []
}`
I need to get debug information or trace info from block, I run 
`./gochain attach ws://localhost:8546
Welcome to the GoChain JavaScript console!
instance: GoChain/v2.2.20/linux-amd64/go1.10.4
 modules: debug:1.0 eth:1.0 net:1.0 rpc:1.0 web3:1.0
`
`eth.getTransactionFromBlock(0x3E8)
null
`
In result i cant spin up blockscout. 
Any ideas why or what miss configured.

**Comment by KursLabIgor** [comment]
weird, i saw that getTransactionFromBlock takes one parameter. What i need to do it is spin up blockscout to gochain and currently i cant since some data in chain absent. that's why i decided to check historical data directly in chain.

**Comment by KursLabIgor** [comment]
@jmank88 
here is return value after execute command: 
`debug.traceBlockByNumber("0x3CFA4E")
[{
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}, {
    result: {
      failed: false,
      gas: 21000,
      returnValue: "",
      structLogs: []
    }
}]
> debug.traceBlockByNumber("0x3CFA4E")
Error: required historical state unavailable
    at web3.js:3143:20
    at web3.js:6380:15
    at web3.js:5097:36
    at <anonymous>:1:1

> debug.traceBlockByNumber("0x3CFA4E")
Error: required historical state unavailable
    at web3.js:3143:20
    at web3.js:6380:15
    at web3.js:5097:36
    at <anonymous>:1:1`

What can be reason of such behavior same command first time return value. then no ?

**Comment by jmank88** [comment]
AFAIK `debug.traceBlockByNumber` replays the block requested, which requires the state after the previous block, which is no longer available in this case (`Error: required historical state unavailable`). This suggests that `--gcmode "archive"` is not functioning. Did you include that flag from the very first execution? I'm not sure it can be added later.

**Comment by KursLabIgor** [comment]
@jmank88 today i removed db folder and start sync again for sure that parameters set. i'll update you with results.

**Comment by jmank88** [comment]
You should be able to confirm whether it is working or not pretty quickly, because it normally only caches the last 128 states IIRC (w/o archive). So you could query, for example, the balance of an account at block 1 to test it out.
Here is an example where the genesis state is available:
```
curl -X POST -H 'Content-Type:application/json' --data '{"jsonrpc":"2.0","id":1,"method":"eth_getBalance","params":["0xc94770007dda54cF92009BFF0dE90c06F603a09f","0x0"]}' https://rpc.gochain.io

{"jsonrpc":"2.0","id":1,"result":"0x0"}
```
as well as 'latest':
```
curl -X POST -H 'Content-Type:application/json' --data '{"jsonrpc":"2.0","id":1,"method":"eth_getBalance","params":["0xc94770007dda54cF92009BFF0dE90c06F603a09f","latest"]}' https://rpc.gochain.io

{"jsonrpc":"2.0","id":1,"result":"0x0"}
```
but block 1 is not:
```
curl -X POST -H 'Content-Type:application/json' --data '{"jsonrpc":"2.0","id":1,"method":"eth_getBalance","params":["0xc94770007dda54cF92009BFF0dE90c06F603a09f","0x1"]}' https://rpc.gochain.io

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"missing trie node 5fafd0c075d61174cdd1ef6f58d274c14761f65bc5d88ab087ed0562f38ec66f (path )"}}
```

If archive is working, then you should be able to query balances at block 1, even after syncing well beyond that.

**Comment by KursLabIgor** [comment]
@jmank88 Response from my node
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"missing trie node 5fafd0c075d61174cdd1ef6f58d274c14761f65bc5d88ab087ed0562f38ec66f (path )"}}

**Comment by jmank88** [comment]
Are you sure that you cleared the data and started from scratch? I was able to run a fresh instance with `gochain --syncmode full --gcmode archive` and query it without any issue.

**Comment by KursLabIgor** [comment]
I'm sure that sync was from scratch but I use with '"', means --syncmode "full" and --gcmode "archive", will try witout quotes. I'll update you with results

**Comment by KursLabIgor** [comment]
meanwhile i dont see any note about sync mode in gochain logs
./gochain --datadir /mnt/sdb/mainnet/node --cache ${GOCHAIN_CACHE:-512} --rpc --ws --wsorigins "*" --rpcapi eth,net,web3,debug --wsapi eth,net,web3,debug --syncmode full --gcmode full

INFO [01-05|09:01:12] Maximum peer count                       ETH=25 LES=0 total=25

INFO [01-05|09:01:12] Starting peer-to-peer node               instance=GoChain/v2.2.20/linux-amd64/go1.10.4

INFO [01-05|09:01:12] Writing default main-net genesis block 

INFO [01-05|09:01:12] Persisted trie from memory database      nodes=1 size=152.00B time=15.088147ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [01-05|09:01:12] Initialised chain configuration          config="{ChainID: 60 Homestead: 0 EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: <nil> EWASM: <nil> Engine: clique}"
INFO [01-05|09:01:12] Initialising GoChain protocol            versions="[63 62]" network=60
ERROR[01-05|09:01:12] Failed to decode database version        encoded=[]
ERROR[01-05|09:01:12] Failed to encode database version        version=3
INFO [01-05|09:01:12] Loaded most recent local header          number=0 hash=5b44a9…acd880 td=1
INFO [01-05|09:01:12] Loaded most recent local full block      number=0 hash=5b44a9…acd880 td=1
INFO [01-05|09:01:12] Loaded most recent local fast block      number=0 hash=5b44a9…acd880 td=1
INFO [01-05|09:01:12] Resetting tx pool                        old=nil newnum=0 newhash=5b44a9…acd880
INFO [01-05|09:01:12] Reset tx pool                            dur=65.06µs
INFO [01-05|09:01:12] Regenerated local transaction journal    transactions=0 accounts=0
INFO [01-05|09:01:12] Starting P2P networking 
INFO [01-05|09:01:14] UDP listener up                          self=enode://aa08475370f3c2ba8888f1566c5ee918e6869b76d69ffd5b2a0fd41b867fb5b3bf8ae9c992466f16f95c3344e63a648ea0fd5540161b282460a6ccef70b03d25@[::]:30303
INFO [01-05|09:01:14] RLPx listener up                         self=enode://aa08475370f3c2ba8888f1566c5ee918e6869b76d69ffd5b2a0fd41b867fb5b3bf8ae9c992466f16f95c3344e63a648ea0fd5540161b282460a6ccef70b03d25@[::]:30303
INFO [01-05|09:01:14] IPC endpoint opened                      url=/mnt/sdb/mainnet/node/gochain.ipc
WARN [01-05|09:01:14] Sanitizing invalid HTTP read timeout     provided=0s updated=30s
WARN [01-05|09:01:14] Sanitizing invalid HTTP write timeout    provided=0s updated=30s
WARN [01-05|09:01:14] Sanitizing invalid HTTP idle timeout     provided=0s updated=2m0s
INFO [01-05|09:01:14] HTTP endpoint opened                     url=http://127.0.0.1:8545             cors= vhosts=localhost
NFO [01-05|09:06:36] Processed Block                          number=77370   hash=4270e5…632806 count=0   diff=5 coinbase=0x3729D2e93e8037F87a2c9Afe34CB84B7069E4dEA parent=f0af9d…4ac576
INFO [01-05|09:06:36] Processed Block                          number=77371   hash=687e95…d48282 count=0   diff=5 coinbase=0xEd7F2e81B0264177e0df8f275f97Fd74Fa51A896 parent=4270e5…632806
INFO [01-05|09:06:36] Processed Block                          number=77372   hash=931dd8…8b3ab9 count=0   diff=5 coinbase=0xF7678AA7F42Bc017f3D6011CA27aeD400647960d parent=687e95…d48282
